sonar.projectKey=REPLACE_WITH_YOUR_SONARCLOUD_PROJECT_KEY
sonar.organization=REPLACE_WITH_YOUR_SONARCLOUD_ORG
sonar.sources=backEnd/src,frontEnd/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/next-env.d.ts,**/cypress/**,**/*.cy.ts,**/*.d.ts
